### ISSUE TITLE
PHP Notice when registering a taxonomy

### ISSUE THREAD

**Issue by sfgarza** [imFORZA/wp-listings-pro#175]
```
[01-Jun-2017 21:47:23 UTC] PHP Notice:  register_taxonomy was called <strong>incorrectly</strong>. Taxonomy names must be between 1 and 32 characters in length. Please see <a href="https://codex.wordpress.org/Debugging_in_WordPress">Debugging in WordPress</a> for more information. (This message was added in version 4.2.0.) in /app/public/wp-includes/functions.php on line 4138
[01-Jun-2017 21:47:23 UTC] PHP Stack trace:
[01-Jun-2017 21:47:23 UTC] PHP   1. {main}() /app/public/wp-admin/plugins.php:0
[01-Jun-2017 21:47:23 UTC] PHP   2. activate_plugin() /app/public/wp-admin/plugins.php:42
[01-Jun-2017 21:47:23 UTC] PHP   3. do_action() /app/public/wp-admin/includes/plugin.php:591
[01-Jun-2017 21:47:23 UTC] PHP   4. WP_Hook->do_action() /app/public/wp-includes/plugin.php:453
[01-Jun-2017 21:47:23 UTC] PHP   5. WP_Hook->apply_filters() /app/public/wp-includes/class-wp-hook.php:323
[01-Jun-2017 21:47:23 UTC] PHP   6. wplpro_activation() /app/public/wp-includes/class-wp-hook.php:298
[01-Jun-2017 21:47:23 UTC] PHP   7. WPLPROAgents_Taxonomies->register_taxonomies() /app/public/wp-content/plugins/wp-listings-pro/wp-listings-pro.php:68
[01-Jun-2017 21:47:23 UTC] PHP   8. register_taxonomy() /app/public/wp-content/plugins/wp-listings-pro/includes/class-taxonomies.php:1138
[01-Jun-2017 21:47:23 UTC] PHP   9. _doing_it_wrong() /app/public/wp-includes/taxonomy.php:380
[01-Jun-2017 21:47:23 UTC] PHP  10. trigger_error() /app/public/wp-includes/functions.php:4138
```

**Comment by dharmendra8787** [comment]
how to resolved this problem .please help me 
About WordPress
UnikCCTV.Com
00 Comments in moderation
New
SEO22 notifications
WP Mail Bank
0
Howdy, digital
Log Out
The Shipment Tracking API Key has not been activated, so the plugin will not get future updates! Click here to activate Shipment Tracking API Key.


Fatal error: Uncaught Error: Call to a member function format() on null in /home/unikcctv/public_html/wp-content/plugins/finpose/classes/orders.class.php:462 Stack trace: #0 /home/unikcctv/public_html/wp-content/plugins/finpose/classes/orders.class.php(59): fin_orders->getOrders() #1 /home/unikcctv/public_html/wp-content/plugins/finpose/admin/class-finpose-admin.php(160): fin_orders->__construct('getOrders') #2 /home/unikcctv/public_html/wp-includes/class-wp-hook.php(292): finpose_Admin->pageDisplay('') #3 /home/unikcctv/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array) #4 /home/unikcctv/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array) #5 /home/unikcctv/public_html/wp-admin/admin.php(259): do_action('accounting_page...') #6 {main} thrown in /home/unikcctv/public_html/wp-content/plugins/finpose/classes/orders.class.php on line 462
